apiVersion: v2
name: odigos-crds
description: CRDs for Odigos Helm Chart
type: application
# 0.0.0 will be replaced by the git tag version on release
version: "0.0.0"
appVersion: "0.0.0"
icon: https://d2q89wckrml3k4.cloudfront.net/logo.png
