version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directory: /autoscaler
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directory: /odiglet
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directory: /scheduler
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directory: /instrumentor
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: npm
    directory: /ui
    schedule:
      day: sunday
      interval: weekly

