version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directories:
      - /autoscaler
      - /odiglet
      - /scheduler
      - /cli
      - /instrumentor
    schedule:
      day: sunday
      interval: weekly
    groups:
      otel-dependencies:
        patterns:
          - "go.opentelemetry.io*"
  - package-ecosystem: gomod
    directory: /autoscaler
    schedule:
      day: sunday
      interval: weekly
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
  - package-ecosystem: gomod
    directory: /odiglet
    schedule:
      day: sunday
      interval: weekly
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
  - package-ecosystem: gomod
    directory: /scheduler
    schedule:
      day: sunday
      interval: weekly
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
  - package-ecosystem: gomod
    directory: /cli
    schedule:
      day: sunday
      interval: weekly
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
  - package-ecosystem: gomod
    directory: /instrumentor
    schedule:
      day: sunday
      interval: weekly
    groups:
      k8s-dependencies:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io*"
  - package-ecosystem: pip
    directory: /odiglet/agents/python
    schedule:
      day: sunday
      interval: weekly
    groups:
      otel-dependencies:
        patterns:
          - "opentelemetry*"