{{- if (include "odigos.secretExists" .) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-ui
  namespace: {{ .Release.Namespace }}
  labels:
    app: central-ui
    odigos.io/system-object: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-ui
  template:
    metadata:
      labels:
        app: central-ui
    spec:
      {{ include "odigos.renderPullSecrets" . | nindent 6 }}
      containers:
        - name: central-ui
          {{ $imageTag := .Values.image.tag | default .Chart.AppVersion }}
          image: {{ template "utils.imageName" (dict "Values" .Values "Component" "central-ui" "Tag" $imageTag) }}
          env:
            - name: CURRENT_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: odigos-central-deployment
          resources:
            requests:
              cpu: {{ .Values.centralUI.resources.requests.cpu }}
              memory: {{ .Values.centralUI.resources.requests.memory }}
            limits:
              cpu: {{ .Values.centralUI.resources.limits.cpu }}
              memory: {{ .Values.centralUI.resources.limits.memory }}
      {{- with .Values.centralUI.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralUI.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralUI.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range .Values.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey | quote }}
          whenUnsatisfiable: {{ .whenUnsatisfiable | quote }}
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: central-ui
      {{- end }}
      {{- end }}
{{- end }}