{{- if and .Values.centralProxy.centralBackendURL .Values.clusterName (include "odigos.secretExists" .)}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: central-proxy
  labels:
    odigos.io/system-object: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: central-proxy
subjects:
  - kind: ServiceAccount
    name: central-proxy
    namespace: {{ .Release.Namespace }}
{{- end }}

