{{ $imageTag := .Values.image.tag | default .Chart.AppVersion }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    odigos.io/system-object: "true"
spec:
  ttlSecondsAfterFinished: 30
  activeDeadlineSeconds: 240
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: cleanup-sa
      containers:
      - name: cleanup
        image: {{ template "utils.imageName" (dict "Values" .Values "Component" "cli" "Tag" $imageTag) }}
        args: ["cleanup", "--yes", "--instrumentation-only", "--namespace", "{{ .Release.Namespace }}"]
        env:
          - name: GOMAXPROCS
            valueFrom:
              resourceFieldRef:
                containerName: cleanup
                resource: limits.cpu
          - name: GOMEMLIMIT
            value: {{ include "odigos.gomemlimitFromResources" (dict "Resources" .Values.cleanup.resources) }}
        resources:
{{ toYaml .Values.cleanup.resources | indent 10 }}
      restartPolicy: Never
      {{ include "odigos.renderPullSecrets" . | nindent 6 }}
