{{- if (include "odigos.secretExists" .) }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: central-backend
    odigos.io/system-object: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-backend
  template:
    metadata:
      labels:
        app: central-backend
    spec:
      serviceAccountName: central-backend
      {{ include "odigos.renderPullSecrets" . | nindent 6 }}
      containers:
        - name: central-backend
          {{- $imageTag := .Values.image.tag | default .Chart.AppVersion }}
          image: {{ template "utils.imageName" (dict "Values" .Values "Component" "central-backend" "Tag" $imageTag) }}
          env:
            - name: ODIGOS_ONPREM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: odigos-central
                  key: ODIGOS_ONPREM_TOKEN
            - name: CURRENT_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: USE_K8S_SECRETS
              value: "true"
            {{- if .Values.auth.enabled }}
            - name: KEYCLOAK_HOST
              value: "http://keycloak:8080"
            - name: KEYCLOAK_SECRET_NAMESPACE
              value: "{{ .Release.Namespace }}"
            - name: KEYCLOAK_SECRET_NAME
              value: "keycloak-admin-credentials"
            {{- end }}
            {{- if .Values.centralBackend.maxMessageSize }}
            - name: MAX_MESSAGE_SIZE
              value: {{ .Values.centralBackend.maxMessageSize | quote }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: odigos-central-deployment
          ports:
            - containerPort: 8081
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 60
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            requests:
              cpu: {{ .Values.centralBackend.resources.requests.cpu }}
              memory: {{ .Values.centralBackend.resources.requests.memory }}
            limits:
              cpu: {{ .Values.centralBackend.resources.limits.cpu }}
              memory: {{ .Values.centralBackend.resources.limits.memory }}
      {{- with .Values.centralBackend.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralBackend.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.centralBackend.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range .Values.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey | quote }}
          whenUnsatisfiable: {{ .whenUnsatisfiable | quote }}
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: central-backend
      {{- end }}
      {{- end }}
{{- end }}
