{{- if (include "odigos.secretExists" .) }}
{{- if and .Values.auth.persistence.enabled (not .Values.auth.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: keycloak
    odigos.io/system-object: "true"
spec:
  accessModes:
    {{- toYaml .Values.auth.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.auth.persistence.size | quote }}
  {{- if .Values.auth.persistence.storageClassName }}
  storageClassName: {{ .Values.auth.persistence.storageClassName | quote }}
  {{- else }}
  storageClassName: ""
  {{- end }}
{{- end }}
{{- end }}
