{{- if (include "odigos.secretExists" .) }}
{{- if not .Values.auth.adminPassword }}
{{- fail "Central admin password is required. Please use --set auth.adminPassword=<your-password>" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
    app: keycloak
type: Opaque
data:
  admin-username: {{ .Values.auth.adminUsername | b64enc }}
  admin-password: {{ .Values.auth.adminPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-oidc-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    odigos.io/system-object: "true"
    app: keycloak
type: Opaque
data:
  provider: {{ .Values.auth.oidcProvider | b64enc }}
  client-id: {{ .Values.auth.oidcClientId | b64enc }}
  client-secret: {{ .Values.auth.oidcClientSecret | b64enc }}
  discovery-url: {{ .Values.auth.oidcDiscoveryUrl | b64enc }}
  tenant-id: {{ .Values.auth.oidcTenantId | b64enc }}
{{- end }}