---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  labels:
    odigos.io/config: "1"
    odigos.io/system-object: "true"
  name: instrumentationinstances.odigos.io
spec:
  group: odigos.io
  names:
    kind: InstrumentationInstance
    listKind: InstrumentationInstanceList
    plural: instrumentationinstances
    singular: instrumentationinstance
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: InstrumentationInstance is the Schema for the InstrumentationInstances
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              containerName:
                description: |-
                  stores the name of the container in the pod where the SDK is running.
                  The pod details can be found as the owner reference on the CR.
                type: string
            required:
            - containerName
            type: object
          status:
            description: |-
              InstrumentationInstanceStatus defines the observed state of InstrumentationInstance
              If the instrumentation is not active, this CR should be deleted
            properties:
              components:
                items:
                  description: |-
                    InstrumentationLibraryStatus defines the observed state of an InstrumentationLibrary.
                    if a library is not active/disable, it should not be included in the status
                  properties:
                    healthy:
                      type: boolean
                    identifyingAttributes:
                      description: |-
                        Attributes that identify the component.
                        The combination of (Name, Type, IdentifyingAttributes) must be unique.
                      items:
                        description: Attribute is a key-value pair that describes
                          a component or instrumentation
                        properties:
                          key:
                            minLength: 1
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                    lastStatusTime:
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the component health.
                        can be omitted if healthy is true
                      maxLength: 32768
                      type: string
                    name:
                      description: for example ("net/http", "@opentelemetry/instrumentation-redis")
                      minLength: 1
                      type: string
                    nonIdentifyingAttributes:
                      description: |-
                        Attributes that do not necessarily identify the component but help describe
                        its characteristics.
                      items:
                        description: Attribute is a key-value pair that describes
                          a component or instrumentation
                        properties:
                          key:
                            minLength: 1
                            type: string
                          value:
                            type: string
                        required:
                        - key
                        - value
                        type: object
                      type: array
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the SDK status.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                      type: string
                    type:
                      enum:
                      - instrumentation
                      - sampler
                      - exporter
                      type: string
                  required:
                  - lastStatusTime
                  - name
                  - type
                  type: object
                type: array
              healthy:
                description: |-
                  Healthy true means that the odigos agent has started the SDK, and there are no errors. User can expect telemetry to be generated.
                  Healthy false means that the agent has stopped and telemetry data is not expected to be generated.
                  Healthy nil means that the agent did not report any health status yet (prefer to always report health status).
                type: boolean
              identifyingAttributes:
                description: |-
                  Attributes that identify the SDK and are reported as resource attributes in the generated telemetry.
                  One can identify if an arbitrary telemetry is generated by this SDK by checking those resource attributes.
                items:
                  description: Attribute is a key-value pair that describes a component
                    or instrumentation
                  properties:
                    key:
                      minLength: 1
                      type: string
                    value:
                      type: string
                  required:
                  - key
                  - value
                  type: object
                type: array
              lastStatusTime:
                format: date-time
                type: string
              message:
                description: |-
                  message is a human readable message indicating details about the SDK general health.
                  can be omitted if healthy is true
                maxLength: 32768
                type: string
              nonIdentifyingAttributes:
                description: Attributes that are not reported as resource attributes
                  but useful to describe characteristics of the SDK.
                items:
                  description: Attribute is a key-value pair that describes a component
                    or instrumentation
                  properties:
                    key:
                      minLength: 1
                      type: string
                    value:
                      type: string
                  required:
                  - key
                  - value
                  type: object
                type: array
              reason:
                description: |-
                  reason contains a programmatic identifier indicating the reason for the component status.
                  Producers of specific condition types may define expected values and meanings for this field,
                  and whether the values are considered a guaranteed API.
                type: string
            required:
            - lastStatusTime
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
