apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: odiglet
  namespace: '{{ .Release.Namespace }}'
  labels:
    odigos.io/system-object: "true"
rules:
# for the collector live config updates, it needs to watch the config map
  - apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - odigos-data-collection
    verbs:
      - get
      - list
      - watch
# for global configs read by the odiglet
  - apiGroups:
      - ''
    resourceNames:
      - effective-config
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
