mode: "statefulset"

config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: ${env:MY_POD_IP}:4318

  exporters:
    debug: {}
    file/trace:
      path: /tmp/trace.json
      rotation:

  service:
    telemetry:
      logs:
        level: "debug"
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - file/trace
          - debug


image:
  repository: otel/opentelemetry-collector-contrib
  tag: "latest"

command:
  name: otelcol-contrib

extraVolumes:
  - name: filevolume
    emptyDir: {}
extraVolumeMounts:
  - mountPath: /tmp
    name: filevolume

extraContainers:
  - name: filecp
    image: busybox
    command: ["sh", "-c", "sleep 36000"]
    volumeMounts:
      - name: filevolume
        mountPath: /tmp