apiVersion: v1
kind: Service
metadata:
  name: odigos-autoscaler
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: webhook-server
      port: 9443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: odigos-autoscaler
