name: full odigos build

on:
  pull_request:
    branches:
      - 'releases/**'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-all-services:
    name: build-all-services
    strategy:
      matrix:
        service: [autoscaler, scheduler, instrumentor, odigos-collector, odiglet, frontend, operator]
        dockerfile_variant: [Dockerfile, Dockerfile.rhel]
        include:
          - service: autoscaler
            dockerfile_path: .
            build-args: SERVICE_NAME=autoscaler
          - service: scheduler
            dockerfile_path: .
            build-args: SERVICE_NAME=scheduler
          - service: instrumentor
            dockerfile_path: .
            build-args: SERVICE_NAME=instrumentor
          - service: odigos-collector
            dockerfile_path: collector
          - service: odiglet
            dockerfile_path: odiglet
          - service: frontend
            dockerfile_path: frontend
          - service: operator
            dockerfile_path: operator
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build ${{ matrix.service }} Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ matrix.service }}:pr-${{ github.event.number }}
          provenance: false
          file: ${{ matrix.dockerfile_path }}/${{ matrix.dockerfile_variant }}
          context: .
          build-args: ${{ matrix.build-args }}

  build-cli:
    runs-on: depot-ubuntu-24.04-8
    steps:
      - uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.0"
      - name: Set up Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: build --snapshot --clean
