name: verify api CRDs
on:
  pull_request:

jobs:
  verify-api-crds:
    defaults:
      run:
        working-directory: ./api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26"
      - name: install controller-gen
        run: make controller-gen
      - name: Check API CRDs
        run: make generate && make manifests
      - name: Verify Generate
        run: |
          if [[ $(git diff --exit-code) ]]; then
            git diff
            echo "api CRDs are not up to date. Please run 'make generate && make manifests' and commit the changes."
            exit 1
          fi
      - name: Generate client files
        run: make generate-client
      - name: Verify Generate
        run: |
          if [[ $(git diff --exit-code) ]]; then
            git diff
            echo "client files are not up to date. Please run 'make generate-client' and commit the changes."
            exit 1
          fi
      - name: Sync CRDs to Helm
        run: make sync-helm-crd
      - name: Verify Helm
        run: |
          if [[ $(git diff --exit-code) ]]; then
            git diff
            echo "Helm CRDs are not up to date. Please run 'make sync-helm-crd' and commit the changes."
            exit 1
          fi
